name       : plasma-browser-integration
version    : 5.25.3
release    : 65
source     :
    - https://cdn.download.kde.org/stable/plasma/5.25.3/plasma-browser-integration-5.25.3.tar.xz : e2ef0e026ce7f572776100133444855ebbc7f8ebb9e59f63c8800f0d994b2ecf
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-3.0-or-later
component  : desktop.kde.core
summary    : Integrate browsers into the Plasma Desktop
description: |
    Components necessary to integrate browsers into the Plasma Desktop.
builddeps  :
    - pkgconfig(Qt5Quick)
    - kactivities-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kfilemetadata-devel
    - kio-devel
    - kitemmodels-devel
    - knotifications-devel
    - krunner-devel
    - plasma-workspace-devel
    - purpose-devel
setup      : |
    %cmake_ninja -DINSTALL_CHROME_MANIFEST=ON \
                -DMOZILLA_DIR=%libdir%/mozilla
build      : |
    %ninja_build
install    : |
    %ninja_install
