name       : plasma-browser-integration
version    : 5.13.5
release    : 6
source     :
    - https://cdn.download.kde.org/stable/plasma/5.13.5/plasma-browser-integration-5.13.5.tar.xz : fe691394c4ddf2c18a1cae2ea78f6a89df57252d91d25e2da8a82761095e172e
license    : GPL-3.0-or-later
component  : desktop.kde.core
summary    : Integrate browsers into the Plasma Desktop
description: |
    Components necessary to integrate browsers into the Plasma Desktop.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libKActivities)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - krunner-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DINSTALL_CHROME_MANIFEST=TRUE \
                -DMOZILLA_DIR=%libdir%/mozilla
build      : |
    %ninja_build
install    : |
    %ninja_install
