name       : plasma-browser-integration
version    : 5.18.2
release    : 30
source     :
    - https://cdn.download.kde.org/stable/plasma/5.18.2/plasma-browser-integration-5.18.2.tar.xz : 988a59559c0399dab6ec2c4ad2d1b9280dd34ce5d031ff32134b3fd9de9ac3b5
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-3.0-or-later
component  : desktop.kde.core
summary    : Integrate browsers into the Plasma Desktop
description: |
    Components necessary to integrate browsers into the Plasma Desktop.
builddeps  :
    - pkgconfig(libKActivities)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kfilemetadata-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - krunner-devel
    - kwindowsystem-devel
    - purpose-devel
setup      : |
    %cmake_ninja -DINSTALL_CHROME_MANIFEST=TRUE \
                -DMOZILLA_DIR=%libdir%/mozilla
build      : |
    %ninja_build
install    : |
    %ninja_install
