name       : plasma-browser-integration
version    : 5.22.1
release    : 50
source     :
    - https://cdn.download.kde.org/stable/plasma/5.22.1/plasma-browser-integration-5.22.1.tar.xz : f88543779964c46120541f01fbefdb13f8f06061fb3f3418454598087a2e5fe6
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-3.0-or-later
component  : desktop.kde.core
summary    : Integrate browsers into the Plasma Desktop
description: |
    Components necessary to integrate browsers into the Plasma Desktop.
builddeps  :
    - pkgconfig(Qt5Quick)
    - kactivities-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kfilemetadata-devel
    - kio-devel
    - kitemmodels-devel
    - knotifications-devel
    - krunner-devel
    - plasma-workspace-devel
    - purpose-devel
setup      : |
    %cmake_ninja -DINSTALL_CHROME_MANIFEST=ON \
                -DMOZILLA_DIR=%libdir%/mozilla
build      : |
    %ninja_build
install    : |
    %ninja_install
