name       : plasma-browser-integration
version    : 5.16.2
release    : 20
source     :
    - https://cdn.download.kde.org/stable/plasma/5.16.2/plasma-browser-integration-5.16.2.tar.xz : b58e1bd8a28b10c8abe8d725fe63f0cd171f752a3e81151b5c98217daa3aaf25
license    : GPL-3.0-or-later
component  : desktop.kde.core
summary    : Integrate browsers into the Plasma Desktop
description: |
    Components necessary to integrate browsers into the Plasma Desktop.
builddeps  :
    - pkgconfig(libKActivities)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdbusaddons-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - krunner-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DINSTALL_CHROME_MANIFEST=TRUE \
                -DMOZILLA_DIR=%libdir%/mozilla
build      : |
    %ninja_build
install    : |
    %ninja_install
