name       : plasma-browser-integration
version    : 5.22.5
release    : 53
source     :
    - https://cdn.download.kde.org/stable/plasma/5.22.5/plasma-browser-integration-5.22.5.tar.xz : 0ef1c9440392f028167ed5c158fe7395324f70b94056d03fe2534c9b1a267ffe
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-3.0-or-later
component  : desktop.kde.core
summary    : Integrate browsers into the Plasma Desktop
description: |
    Components necessary to integrate browsers into the Plasma Desktop.
builddeps  :
    - pkgconfig(Qt5Quick)
    - kactivities-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kfilemetadata-devel
    - kio-devel
    - kitemmodels-devel
    - knotifications-devel
    - krunner-devel
    - plasma-workspace-devel
    - purpose-devel
setup      : |
    %cmake_ninja -DINSTALL_CHROME_MANIFEST=ON \
                -DMOZILLA_DIR=%libdir%/mozilla
build      : |
    %ninja_build
install    : |
    %ninja_install
