name       : plasma-browser-integration
version    : 5.23.5
release    : 59
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.5/plasma-browser-integration-5.23.5.tar.xz : d74b043256d4eaf6c3b44507959eb28761e417ecd2fb7cc98b34aec77294894b
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-3.0-or-later
component  : desktop.kde.core
summary    : Integrate browsers into the Plasma Desktop
description: |
    Components necessary to integrate browsers into the Plasma Desktop.
builddeps  :
    - pkgconfig(Qt5Quick)
    - kactivities-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kfilemetadata-devel
    - kio-devel
    - kitemmodels-devel
    - knotifications-devel
    - krunner-devel
    - plasma-workspace-devel
    - purpose-devel
setup      : |
    %cmake_ninja -DINSTALL_CHROME_MANIFEST=ON \
                -DMOZILLA_DIR=%libdir%/mozilla
build      : |
    %ninja_build
install    : |
    %ninja_install
