name       : plasma-browser-integration
version    : 5.15.3
release    : 15
source     :
    - https://cdn.download.kde.org/stable/plasma/5.15.3/plasma-browser-integration-5.15.3.tar.xz : 59c984d174ab484899b9b1d7d4600f5be3152d8bbed2fb8f44cdbf617e510ad6
license    : GPL-3.0-or-later
component  : desktop.kde.core
summary    : Integrate browsers into the Plasma Desktop
description: |
    Components necessary to integrate browsers into the Plasma Desktop.
builddeps  :
    - pkgconfig(libKActivities)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdbusaddons-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - krunner-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DINSTALL_CHROME_MANIFEST=TRUE \
                -DMOZILLA_DIR=%libdir%/mozilla
build      : |
    %ninja_build
install    : |
    %ninja_install
