name       : plasma-browser-integration
version    : 5.20.4
release    : 42
source     :
    - https://cdn.download.kde.org/stable/plasma/5.20.4/plasma-browser-integration-5.20.4.tar.xz : 55057e4f15a1e8b2d2f0489d32f95bb89f610ae99184b587ba90f7db0e8292b4
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-3.0-or-later
component  : desktop.kde.core
summary    : Integrate browsers into the Plasma Desktop
description: |
    Components necessary to integrate browsers into the Plasma Desktop.
builddeps  :
    - pkgconfig(libKActivities)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kfilemetadata-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - krunner-devel
    - kwindowsystem-devel
    - purpose-devel
setup      : |
    %cmake_ninja -DINSTALL_CHROME_MANIFEST=ON \
                -DMOZILLA_DIR=%libdir%/mozilla
build      : |
    %ninja_build
install    : |
    %ninja_install
