name       : plasma-browser-integration
version    : 5.27.4
release    : 69
source     :
    - https://cdn.download.kde.org/stable/plasma/5.27.4/plasma-browser-integration-5.27.4.tar.xz : d37af781b11ec1622476b51af25ac82c8d2373bb8ff9c23981cb8a1c6d97f466
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-3.0-or-later
component  : desktop.kde.core
summary    : Integrate browsers into the Plasma Desktop
description: |
    Components necessary to integrate browsers into the Plasma Desktop.
builddeps  :
    - pkgconfig(Qt5Quick)
    - kactivities-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kfilemetadata-devel
    - kio-devel
    - kitemmodels-devel
    - knotifications-devel
    - krunner-devel
    - plasma-workspace-devel
    - purpose-devel
setup      : |
    %cmake_ninja -DINSTALL_CHROME_MANIFEST=ON \
                -DMOZILLA_DIR=%libdir%/mozilla
build      : |
    %ninja_build
install    : |
    %ninja_install
