name       : plasma-browser-integration
version    : 5.15.2
release    : 14
source     :
    - https://cdn.download.kde.org/stable/plasma/5.15.2/plasma-browser-integration-5.15.2.tar.xz : e9d8d14455cd6f7851e1e3e6cba46fa4705d152ad8971867e6e74b30393fb702
license    : GPL-3.0-or-later
component  : desktop.kde.core
summary    : Integrate browsers into the Plasma Desktop
description: |
    Components necessary to integrate browsers into the Plasma Desktop.
builddeps  :
    - pkgconfig(libKActivities)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdbusaddons-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - krunner-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DINSTALL_CHROME_MANIFEST=TRUE \
                -DMOZILLA_DIR=%libdir%/mozilla
build      : |
    %ninja_build
install    : |
    %ninja_install
