name       : plasma-browser-integration
version    : 5.19.4
release    : 36
source     :
    - https://cdn.download.kde.org/stable/plasma/5.19.4/plasma-browser-integration-5.19.4.tar.xz : a947307b6e8095007e7488e9f5c3d87afdeb538c88a1b6f194bc99533098a5a5
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-3.0-or-later
component  : desktop.kde.core
summary    : Integrate browsers into the Plasma Desktop
description: |
    Components necessary to integrate browsers into the Plasma Desktop.
builddeps  :
    - pkgconfig(libKActivities)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kfilemetadata-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - krunner-devel
    - kwindowsystem-devel
    - purpose-devel
setup      : |
    %cmake_ninja -DINSTALL_CHROME_MANIFEST=TRUE \
                -DMOZILLA_DIR=%libdir%/mozilla
build      : |
    %ninja_build
install    : |
    %ninja_install
